project:
  type: website

website:
  title: "Cal Adapt Scientific Guidance"
  search: true
  page-navigation: true
  bread-crumbs: true
  open-graph: true
  navbar:
    left:
      - href: glossary.qmd
        text: Glossary
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    citation: true
  pdf: default
